# Generated by Django 2.1 on 2018-09-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('keywords', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('concepts', models.CharField(max_length=128)),
                ('entities', models.CharField(max_length=128)),
                ('categories', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=128)),
            ],
        ),
    ]
