# Generated by Django 2.1 on 2018-11-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_delete_comparesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('java', models.TextField(blank=True, null=True)),
                ('javascript', models.TextField(blank=True, null=True)),
                ('php', models.TextField(blank=True, null=True)),
                ('python', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
